package main

// Shell completion, generated from the registry.
//
// A hand-written completion script is a fourth copy of the command list, and
// this package has already watched three copies of that list drift apart. This
// one is built from the same tables dispatch and help read, so it cannot
// describe a command that does not exist or miss one that does — and a test
// asserts exactly that for all four shells.
//
// Flags are deliberately not completed. They differ per command, and a stale
// list of them would be worse than none: a completion that offers a flag the
// command does not take teaches the wrong thing confidently.

import (
	"flag"
	"fmt"
	"sort"
	"strings"
)

// --- completion ---

type completionOpts struct{ shell string }

var completionCmd = cmd(Command{
	Name: "completion", Usage: "<bash|zsh|fish|powershell>",
	Short: "print a shell completion script",
	Long: "Generated from the registry, so it cannot describe a command that does\n" +
		"not exist or miss one that does — the same list dispatch and help are\n" +
		"built from.\n\n" +
		"  bash        graphene completion bash       > /etc/bash_completion.d/graphene\n" +
		"  zsh         graphene completion zsh        > \"${fpath[1]}/_graphene\"\n" +
		"  fish        graphene completion fish       > ~/.config/fish/completions/graphene.fish\n" +
		"  powershell  graphene completion powershell >> $PROFILE\n\n" +
		"It completes groups and verbs. Flags are not completed: they differ per\n" +
		"command and a stale list of them would be worse than none.",
	Open: OpenNone, Streams: true, Tier: CtxAdvisory,
},
	func(fs *flag.FlagSet, o *completionOpts) {},
	runCompletion)

func runCompletion(cx *Context, _ *completionOpts) (Result, error) {
	var r Result
	shell := cx.Target
	switch shell {
	case "bash":
		fmt.Fprint(cx.Out, bashCompletion())
	case "zsh":
		fmt.Fprint(cx.Out, zshCompletion())
	case "fish":
		fmt.Fprint(cx.Out, fishCompletion())
	case "powershell", "pwsh":
		fmt.Fprint(cx.Out, powershellCompletion())
	case "":
		return r, Usagef("need a shell: bash, zsh, fish or powershell")
	default:
		return r, Usagef("no completion for %q; want bash, zsh, fish or powershell", shell)
	}
	return r, nil
}

// completionTree is the registry as completion needs it: the top-level words,
// and the verbs under each group.
//
// Built here rather than written out, which is the whole point — a hand-written
// completion script is a fourth copy of the command list, and this package has
// already watched three copies drift apart.
func completionTree() (top []string, verbs map[string][]string) {
	seen := map[string]bool{}
	add := func(s string) {
		if !seen[s] {
			seen[s] = true
			top = append(top, s)
		}
	}
	verbs = map[string][]string{}

	for _, g := range visibleGroups() {
		add(g)
		for _, c := range visible(g) {
			verbs[g] = append(verbs[g], c.Name)
		}
		sort.Strings(verbs[g])
	}
	// Read from the lookup tables initRegistry builds, not from the registry
	// slice. Reaching for the slice here would make completionCmd depend on
	// registry, which contains completionCmd — an initialisation cycle the
	// compiler refuses, and rightly: the tables are the built form, and this is
	// reading the built form.
	for path, c := range byPath {
		if c.Group == "" && !c.Hidden {
			add(path)
		}
	}
	add("help")
	sort.Strings(top)
	return top, verbs
}

func bashCompletion() string {
	top, verbs := completionTree()
	var b strings.Builder

	b.WriteString("# graphene completion, generated by `graphene completion bash`.\n")
	b.WriteString("_graphene() {\n")
	b.WriteString("  local cur prev\n")
	b.WriteString("  cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	b.WriteString("  prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n")
	b.WriteString("  if [ \"$COMP_CWORD\" -le 1 ]; then\n")
	fmt.Fprintf(&b, "    COMPREPLY=( $(compgen -W %q -- \"$cur\") )\n", strings.Join(top, " "))
	b.WriteString("    return\n  fi\n")
	b.WriteString("  case \"$prev\" in\n")
	for _, g := range sortedKeys(verbs) {
		fmt.Fprintf(&b, "    %s) COMPREPLY=( $(compgen -W %q -- \"$cur\") ); return ;;\n",
			g, strings.Join(verbs[g], " "))
	}
	b.WriteString("  esac\n")
	// Everything else is a path: every command's operand is a directory or a
	// file, so falling through to the filesystem is right rather than lazy.
	b.WriteString("  COMPREPLY=( $(compgen -f -- \"$cur\") )\n")
	b.WriteString("}\ncomplete -o filenames -F _graphene graphene\n")
	return b.String()
}

func zshCompletion() string {
	top, verbs := completionTree()
	var b strings.Builder

	b.WriteString("#compdef graphene\n")
	b.WriteString("# generated by `graphene completion zsh`.\n")
	b.WriteString("_graphene() {\n")
	b.WriteString("  local -a top\n")
	fmt.Fprintf(&b, "  top=(%s)\n", strings.Join(top, " "))
	b.WriteString("  if (( CURRENT == 2 )); then\n")
	b.WriteString("    _describe 'command' top\n    return\n  fi\n")
	b.WriteString("  case \"${words[2]}\" in\n")
	for _, g := range sortedKeys(verbs) {
		fmt.Fprintf(&b, "    %s) if (( CURRENT == 3 )); then _values 'verb' %s; return; fi ;;\n",
			g, strings.Join(verbs[g], " "))
	}
	b.WriteString("  esac\n")
	b.WriteString("  _files\n}\n")
	b.WriteString("compdef _graphene graphene\n")
	return b.String()
}

func fishCompletion() string {
	top, verbs := completionTree()
	var b strings.Builder

	b.WriteString("# generated by `graphene completion fish`.\n")
	for _, t := range top {
		fmt.Fprintf(&b, "complete -c graphene -n '__fish_use_subcommand' -a %q\n", t)
	}
	for _, g := range sortedKeys(verbs) {
		for _, v := range verbs[g] {
			fmt.Fprintf(&b, "complete -c graphene -n '__fish_seen_subcommand_from %s' -a %q\n", g, v)
		}
	}
	return b.String()
}

func powershellCompletion() string {
	top, verbs := completionTree()
	var b strings.Builder

	b.WriteString("# generated by `graphene completion powershell`.\n")
	b.WriteString("Register-ArgumentCompleter -Native -CommandName graphene -ScriptBlock {\n")
	b.WriteString("  param($wordToComplete, $commandAst, $cursorPosition)\n")
	b.WriteString("  $words = $commandAst.CommandElements | Select-Object -Skip 1 | ForEach-Object { $_.ToString() }\n")
	fmt.Fprintf(&b, "  $top = @(%s)\n", quoteList(top))
	b.WriteString("  $verbs = @{\n")
	for _, g := range sortedKeys(verbs) {
		fmt.Fprintf(&b, "    '%s' = @(%s)\n", g, quoteList(verbs[g]))
	}
	b.WriteString("  }\n")
	b.WriteString("  $candidates = $top\n")
	b.WriteString("  if ($words.Count -ge 1 -and $verbs.ContainsKey($words[0])) { $candidates = $verbs[$words[0]] }\n")
	b.WriteString("  $candidates | Where-Object { $_ -like \"$wordToComplete*\" } | ForEach-Object {\n")
	b.WriteString("    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)\n")
	b.WriteString("  }\n}\n")
	return b.String()
}

func quoteList(items []string) string {
	parts := make([]string, len(items))
	for i, s := range items {
		parts[i] = "'" + s + "'"
	}
	return strings.Join(parts, ",")
}

func sortedKeys(m map[string][]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
