package disk

// Ordering the reverse index: the one sort a compaction cannot do in memory.
//
// # Why a sort is needed at all
//
// GPIX is generated key by key, so its entries come out in (key, value, id)
// order. GPIR answers the opposite question — what is this entity indexed under
// — and is binary-searched by id, so it needs (id, key, value) order. There is
// no walk of the index that produces the second order and also produces the
// valueOff each reverse entry carries, because a valueOff is the offset of a
// value inside a run that the forward pass is in the middle of writing. So the
// entries are generated by the forward pass and ordered afterwards.
//
// # Why not in memory
//
// 24 bytes per entry. At the shape docs/MEMORY_MODEL.md measures that is 672
// MiB, held during a compaction that is already holding a freshly built CSR —
// which is the allocation the disk-resident index exists to remove, reappearing
// in the code that writes it. So the sort is external: runs of a bounded number
// of entries are sorted in memory and spilled, and the section is written by
// merging them.
//
// The memory a sort of any size costs is therefore one chunk plus one small read
// buffer per run, and both are constants. The IO is one sequential write and one
// sequential read of 24 bytes per entry, on a path that is already writing the
// image.
//
// # Why the small case has no sort at all
//
// A store whose entries fit in one chunk is sorted in place and emitted, with no
// spill file opened and no merge. That is every test in this package and every
// store below roughly a quarter of a million entries. The merge path is not a
// fallback for an unlikely shape — it is what the store this program is aimed at
// takes — so it is exercised with the chunk size set to a handful of entries
// rather than left to a fixture nobody builds.
//
// # Determinism
//
// The section's bytes are part of the image's digest, so two compactions of the
// same index must order the entries identically. (id, keyID, valueOff) is a total
// order over the entries a valid index produces: an entity is indexed under one
// value of one key at most once, so no two entries share all three. The sort
// therefore needs no tie-break and the merge needs no stable-run bookkeeping.

import (
	"encoding/binary"
	"fmt"
	"io"
	"slices"
)

const (
	// gpirSortChunkEntries is how many entries are held and sorted in memory at
	// once: 32 Ki entries, three quarters of a megabyte.
	//
	// Small on purpose, like gpixVtabMemCap. A chunk ten times the size would
	// spare a store of a few hundred thousand entries its spill file, and that is
	// not the trade this program is making: memory is what it is spending down and
	// sequential disk is what it is allowed to spend. At the shape
	// docs/MEMORY_MODEL.md measures this is ~850 runs, which the budget below
	// merges in one pass.
	gpirSortChunkEntries = 32 << 10

	// gpirMergeReadBudget bounds every run reader's buffer together and
	// gpirMaxRunBuffer bounds one of them, so that the merge costs a constant
	// however many runs it merges and does not spend the whole budget on two. A
	// thousand runs get small buffers rather than a thousand large ones.
	gpirMergeReadBudget = 2 << 20
	gpirMaxRunBuffer    = 64 << 10

	// gpirMinRunBuffer is the floor on one reader's buffer. Four entries rather
	// than one so that the common case reads ahead even when the budget is
	// divided a thousand ways.
	gpirMinRunBuffer = 4 * gpirEntrySize
)

// putGPIREntry encodes one entry into dst, which must hold gpirEntrySize bytes.
//
// The two pad bytes are written as zeros explicitly. They are part of the
// image's digest, so "whatever was in the buffer" is not an option: it would
// make two compactions of identical content produce different bytes, which is
// the one thing canonical serialisation exists to prevent.
func putGPIREntry(dst []byte, e gpirEntry) {
	binary.LittleEndian.PutUint64(dst[0:8], e.ID)
	binary.LittleEndian.PutUint16(dst[8:10], e.KeyID)
	binary.LittleEndian.PutUint16(dst[10:12], 0)
	binary.LittleEndian.PutUint32(dst[12:16], e.ValLen)
	binary.LittleEndian.PutUint64(dst[16:24], e.ValueOff)
}

// gpirEntryLess is the section's order.
func gpirEntryLess(a, b gpirEntry) int {
	switch {
	case a.ID != b.ID:
		if a.ID < b.ID {
			return -1
		}
		return 1
	case a.KeyID != b.KeyID:
		if a.KeyID < b.KeyID {
			return -1
		}
		return 1
	case a.ValueOff != b.ValueOff:
		if a.ValueOff < b.ValueOff {
			return -1
		}
		return 1
	}
	return 0
}

// gpirRun is one sorted chunk inside the spill.
type gpirRun struct {
	off   uint64
	count uint64
}

// gpirSorter accumulates reverse entries and yields them in section order.
//
// Fill it with add and drain it once with emit. A failure to spill is held by the
// spill and reported from emit, for the reason spillBuffer gives: a caller adding
// an entry in the middle of writing a section can do nothing with an IO error
// that it will not already do when the image write fails.
type gpirSorter struct {
	spill *spillBuffer
	chunk int

	// mergeBudget and maxRunBuffer are emit's, held here because that is where
	// the sizes a caller chose have to arrive: the merge happens once, at the
	// end, and there is nowhere else to pass them in.
	mergeBudget  int
	maxRunBuffer int

	buf     []gpirEntry
	scratch []byte
	runs    []gpirRun
	n       uint64
	drained bool
}

// newGPIRSorter returns a sorter spilling into dir and sized by b. Every zero
// field of b takes that threshold's default.
func newGPIRSorter(dir string, b compactBuffers) *gpirSorter {
	b = b.resolved()
	// One chunk's worth of spill in memory, so that a sort producing a single run
	// touches no file and one producing two does.
	return &gpirSorter{
		spill:        newSpill(dir, b.revChunk*gpirEntrySize),
		chunk:        b.revChunk,
		mergeBudget:  b.mergeBudget,
		maxRunBuffer: b.maxRunBuffer,
	}
}

// add records one entry.
func (s *gpirSorter) add(e gpirEntry) {
	if s.buf == nil {
		// One allocation for the chunk, on the first entry rather than at
		// construction: a store with no edge properties builds an edge sorter and
		// must not pay for it, and a store with many must not pay the ~5x that
		// growing into the chunk by append would cost. See spillBuffer.write.
		s.buf = make([]gpirEntry, 0, s.chunk)
	}
	s.buf = append(s.buf, e)
	s.n++
	if len(s.buf) >= s.chunk {
		s.spillRun()
	}
}

// count is how many entries have been added. GPIR's header carries both kinds'
// counts and precedes the entries, so this is read before emit runs.
func (s *gpirSorter) count() uint64 { return s.n }

// spillRun sorts what is buffered and appends it to the spill as one run.
func (s *gpirSorter) spillRun() {
	if len(s.buf) == 0 {
		return
	}
	slices.SortFunc(s.buf, gpirEntryLess)
	if s.scratch == nil {
		s.scratch = make([]byte, 0, 64<<10)
	}
	off := s.spill.len()
	dst := s.scratch[:0]
	for _, e := range s.buf {
		if len(dst)+gpirEntrySize > cap(dst) {
			s.spill.write(dst)
			dst = dst[:0]
		}
		dst = dst[:len(dst)+gpirEntrySize]
		putGPIREntry(dst[len(dst)-gpirEntrySize:], e)
	}
	s.spill.write(dst)
	s.runs = append(s.runs, gpirRun{off: off, count: uint64(len(s.buf))})
	s.buf = s.buf[:0]
}

// emit calls fn for every entry in (id, keyID, valueOff) order, once.
func (s *gpirSorter) emit(fn func(gpirEntry)) error {
	if s.drained {
		return fmt.Errorf("gpir: sorter drained twice")
	}
	s.drained = true

	// Nothing was spilled: the whole section is one chunk, so it is sorted where
	// it is and no file was ever opened.
	if len(s.runs) == 0 {
		slices.SortFunc(s.buf, gpirEntryLess)
		for _, e := range s.buf {
			fn(e)
		}
		return nil
	}

	s.spillRun()
	// The chunk is released before the merge allocates its read buffers, so the
	// two are not held at once.
	s.buf, s.scratch = nil, nil
	if s.spill.err != nil {
		return s.spill.err
	}

	bufSize := min(s.mergeBudget/len(s.runs), s.maxRunBuffer)
	bufSize -= bufSize % gpirEntrySize
	if bufSize < gpirMinRunBuffer {
		bufSize = gpirMinRunBuffer
	}
	heap := make([]*gpirRunReader, 0, len(s.runs))
	for _, run := range s.runs {
		r, err := s.spill.section(run.off, run.count*gpirEntrySize)
		if err != nil {
			return err
		}
		rr := &gpirRunReader{r: r, left: run.count, buf: make([]byte, bufSize)}
		if !rr.advance() {
			if rr.err != nil {
				return rr.err
			}
			continue
		}
		heap = append(heap, rr)
	}
	for i := len(heap)/2 - 1; i >= 0; i-- {
		gpirSiftDown(heap, i)
	}

	for len(heap) > 0 {
		r := heap[0]
		fn(r.head)
		if r.advance() {
			gpirSiftDown(heap, 0)
			continue
		}
		if r.err != nil {
			return r.err
		}
		last := len(heap) - 1
		heap[0] = heap[last]
		heap = heap[:last]
		if len(heap) > 0 {
			gpirSiftDown(heap, 0)
		}
	}
	return nil
}

// close releases the sorter's spill.
func (s *gpirSorter) close() { s.spill.close() }

// gpirRunReader reads one sorted run, one buffer at a time.
type gpirRunReader struct {
	r      io.Reader
	buf    []byte
	pos    int
	filled int
	left   uint64
	head   gpirEntry
	err    error
}

// advance loads the next entry into head, reporting whether there was one.
//
// A false return with err nil is the end of the run; a false return with err set
// is a read that failed, and the caller checks which.
func (r *gpirRunReader) advance() bool {
	if r.err != nil || r.left == 0 {
		return false
	}
	if r.pos+gpirEntrySize > r.filled {
		// Never a partial entry: the buffer's length and every read below are
		// multiples of gpirEntrySize, so filled is one too and pos reaches it
		// exactly. Without that the refill here would drop the tail bytes of an
		// entry straddling two reads.
		want := int(min(uint64(len(r.buf)), r.left*gpirEntrySize))
		n, err := io.ReadFull(r.r, r.buf[:want])
		if err != nil {
			// Short of what the run's own length says it holds. The spill is a
			// file this process wrote moments ago, so this is a real IO failure
			// rather than a malformed input, and it aborts the image.
			r.err = fmt.Errorf("gpir: read run: %w", err)
			return false
		}
		r.pos, r.filled = 0, n
	}
	r.head = gpirEntryAt(r.buf[r.pos:], 0)
	r.pos += gpirEntrySize
	r.left--
	return true
}

// gpirSiftDown restores the heap order at i, comparing readers by their heads.
//
// Written out rather than taken from container/heap because a merge only ever
// replaces the root and sifts: there is no Push and no Pop, so the interface the
// package requires would be three methods used by nothing, dispatched once per
// comparison over every entry in the index.
func gpirSiftDown(h []*gpirRunReader, i int) {
	n := len(h)
	for {
		l, r := 2*i+1, 2*i+2
		small := i
		if l < n && gpirEntryLess(h[l].head, h[small].head) < 0 {
			small = l
		}
		if r < n && gpirEntryLess(h[r].head, h[small].head) < 0 {
			small = r
		}
		if small == i {
			return
		}
		h[i], h[small] = h[small], h[i]
		i = small
	}
}
